services:
  vaultui:
    image: node:22-alpine
    container_name: vault-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      VAULT_API_URL: "http://localhost:7860"
      VAULT_API_WEBSOCKET_URL: "ws://localhost:8000"
  storybook:
    image: truechart/vault-storybook:latest
    container_name: storybook
    restart: unless-stopped
    ports:
      - "7070:8080"
